<a href="https://colab.research.google.com/github/2424hugo/PytorchFreeCodeCamp/blob/main/00_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


## Intro to tensors

## Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get item as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[3, 4, 5],
                        [1, 2, 3],
                        [4, 6, 8]],
                       [[5, 4, 5],
                        [1, 9, 3],
                        [4, 0, 8]]])
TENSOR

tensor([[[3, 4, 5],
         [1, 2, 3],
         [4, 6, 8]],

        [[5, 4, 5],
         [1, 9, 3],
         [4, 0, 8]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0]

tensor([[3, 4, 5],
        [1, 2, 3],
        [4, 6, 8]])

### Random Tensors

Why random tensors?

Random tensors are important because NN start with random numbers and adjust the numbers.

'Start with random nubmers-> Look at data -> update random numbers -> look at data -> update random numbers

In [ ]:
# Create random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7350, 0.9188, 0.9069, 0.4941],
        [0.8090, 0.2070, 0.5199, 0.3139],
        [0.2501, 0.2759, 0.2320, 0.0987]])

In [ ]:
# Create random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Using torch.range()
one_to_ten = torch.arange(start=1,end = 11, step =1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what dtype is the tensor
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether to track gradient with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.device

device(type='cpu')

In [ ]:
# Float 32 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)