<a href="https://colab.research.google.com/github/2424hugo/PytorchFreeCodeCamp/blob/main/00_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


## Intro to tensors

## Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get item as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor
TENSOR = torch.tensor([[[3, 4, 5],
                        [1, 2, 3],
                        [4, 6, 8]],
                       [[5, 4, 5],
                        [1, 9, 3],
                        [4, 0, 8]]])
TENSOR

tensor([[[3, 4, 5],
         [1, 2, 3],
         [4, 6, 8]],

        [[5, 4, 5],
         [1, 9, 3],
         [4, 0, 8]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 3, 3])

In [15]:
TENSOR[0]

tensor([[3, 4, 5],
        [1, 2, 3],
        [4, 6, 8]])

### Random Tensors

Why random tensors?

Random tensors are important because NN start with random numbers and adjust the numbers.

'Start with random nubmers-> Look at data -> update random numbers -> look at data -> update random numbers

In [16]:
# Create random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6918, 0.9987, 0.0849, 0.9932],
        [0.6597, 0.0023, 0.5355, 0.3406],
        [0.2020, 0.0370, 0.6814, 0.9052]])

In [17]:
# Create random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
# Using torch.range()
one_to_ten = torch.arange(start=1,end = 11, step =1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what dtype is the tensor
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether to track gradient with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.device

device(type='cpu')

In [26]:
# Float 32 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [29]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting info from tensors (tensor attaributes)

1. Tensors not right datatype - 'tonsor_name.dtype'
2. Tensors not right shape - 'tonsor_name.size()/shape'
3. Tensors not on the right device - 'tonsor_name.device'

In [30]:
# Create a tensor
some_tensor = torch.rand([3,4], dtype = torch.float64)
some_tensor

tensor([[0.4643, 0.2083, 0.5979, 0.7087],
        [0.0997, 0.7207, 0.9576, 0.7695],
        [0.3998, 0.9485, 0.7072, 0.8202]], dtype=torch.float64)

In [31]:
# Find out details
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4643, 0.2083, 0.5979, 0.7087],
        [0.0997, 0.7207, 0.9576, 0.7695],
        [0.3998, 0.9485, 0.7072, 0.8202]], dtype=torch.float64)
Datatype of tensor: torch.float64
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors

Tensor opertions include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [32]:
# Create a tensor and add 10
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [33]:
# Multiply by 10
tensor * 10

tensor([10, 20, 30])

In [34]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [35]:
# Try out pytorch inbuild functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [36]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-Wise
2. Matrix Multiplication (dot product)

There are two main rules while performing matrix mutliplication:
1. **Inner dimentions** must match:
* '(3,2) @ (3,2)' won't work
* '(2,3) @ (3,2)' will work
* '(3,2) @ (2,3)' will work
2. The resulting matrix has the shape of the **outer dimensions**


In [58]:
torch.matmul(torch.rand(6,3), torch.rand(3,5)).shape

torch.Size([6, 5])

In [39]:
# Element wise
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [49]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [43]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [48]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 2.44 ms, sys: 0 ns, total: 2.44 ms
Wall time: 2.37 ms


tensor(14)

In [50]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 138 µs, sys: 0 ns, total: 138 µs
Wall time: 144 µs


tensor(14)

### One of the most common errors in DL is shape errors

In [59]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # tensor.mm is same as tensor.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

**Transpose** switches the axes of a given tensor.

In [60]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [61]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [62]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])