<a href="https://colab.research.google.com/github/2424hugo/PytorchFreeCodeCamp/blob/main/00_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


## Intro to tensors

## Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get item as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor
TENSOR = torch.tensor([[[3, 4, 5],
                        [1, 2, 3],
                        [4, 6, 8]],
                       [[5, 4, 5],
                        [1, 9, 3],
                        [4, 0, 8]]])
TENSOR

tensor([[[3, 4, 5],
         [1, 2, 3],
         [4, 6, 8]],

        [[5, 4, 5],
         [1, 9, 3],
         [4, 0, 8]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 3, 3])

In [15]:
TENSOR[0]

tensor([[3, 4, 5],
        [1, 2, 3],
        [4, 6, 8]])

### Random Tensors

Why random tensors?

Random tensors are important because NN start with random numbers and adjust the numbers.

'Start with random nubmers-> Look at data -> update random numbers -> look at data -> update random numbers

In [16]:
# Create random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5175, 0.6537, 0.1423, 0.2302],
        [0.2466, 0.6204, 0.6122, 0.5995],
        [0.8547, 0.3880, 0.2727, 0.6603]])

In [17]:
# Create random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
# Using torch.range()
one_to_ten = torch.arange(start=1,end = 11, step =1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [31]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what dtype is the tensor
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether to track gradient with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.device

device(type='cpu')

In [28]:
# Float 32 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [51]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [43]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting info from tensors (tensor attaributes)

1. Tensors not right datatype - 'tonsor_name.dtype'
2. Tensors not right shape - 'tonsor_name.size()/shape'
3. Tensors not on the right device - 'tonsor_name.device'

In [62]:
# Create a tensor
some_tensor = torch.rand([3,4], dtype = torch.float64)
some_tensor

tensor([[0.1064, 0.9435, 0.4238, 0.9465],
        [0.9123, 0.1332, 0.5755, 0.7378],
        [0.9488, 0.3766, 0.6126, 0.7951]], dtype=torch.float64)

In [63]:
# Find out details
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1064, 0.9435, 0.4238, 0.9465],
        [0.9123, 0.1332, 0.5755, 0.7378],
        [0.9488, 0.3766, 0.6126, 0.7951]], dtype=torch.float64)
Datatype of tensor: torch.float64
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors

Tensor opertions include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [65]:
# Create a tensor and add 10
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [66]:
# Multiply by 10
tensor * 10

tensor([10, 20, 30])

In [67]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [68]:
# Try out pytorch inbuild functions
torch.mul(tensor, 10)

tensor([10, 20, 30])